# Generated by Django 5.0.6 on 2024-06-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('motif', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('confime', 'Confirm'), ('pass', 'Passe'), ('wait', 'En Attente'), ('dispo', 'Disponible'), ('refuse', 'Refuse')], max_length=10)),
                ('moment', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
